import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { PLANS } from '@/lib/billing/plans';
import { BRAND } from '@/lib/brand';

const FAQS = [
  {
    q: 'Where does the market data come from?',
    a: 'Version 1 runs on a deterministic sample data layer, and every report that uses it is labelled "Sample data" in the app and on the PDF. It is generated from the topic itself, so a topic always returns the same market and the scoring is genuinely reproducible. Live Amazon listing data and third-party keyword volume slot into the same interface without any change to the scoring engine.',
  },
  {
    q: 'Is the score generated by AI?',
    a: 'No. The score is a fixed formula over the market data — three weighted factors built from ten individual signals. The same inputs always give the same number. Every report shows the raw input, the normalized value, the weight and the points contributed for each signal, so you can add the column up yourself. The only AI in the product is the Publishing Coach, which explains scores it did not calculate.',
  },
  {
    q: 'What actually decides GO, MAYBE or SKIP?',
    a: 'The headline score, plus two guardrails. A total of 70 or more is a GO, 45 to 69 is a MAYBE, below 45 is a SKIP. On top of that, a topic cannot earn a GO if demand alone scores under 50 or competition scores under 35, and any topic with demand below 22 is a SKIP whatever else is true. Every report states which rule produced its verdict.',
  },
  {
    q: 'How accurate are the sales and revenue estimates?',
    a: 'They are estimates derived from Best Sellers Rank using a published power-law curve, not reported sales figures. Amazon does not release per-title sales, so nobody can offer more than a modelled number. Treat the ranges as an order of magnitude for comparing topics against each other, which is what they are built for.',
  },
  {
    q: 'How many validations do I get?',
    a: `Every account starts with ${PLANS.free.validationsPerCycle} free validations, no card required. Standard is ${PLANS.standard.validationsPerCycle} a month, Pro is ${PLANS.pro.validationsPerCycle}. The counter resets at the start of each billing cycle and your remaining credits are shown on every page of the app.`,
  },
  {
    q: 'What happens when I hit my limit?',
    a: 'Validations stop and everything else keeps working — saved reports, projects, PDF exports and the other six tools are all still available. You can upgrade at any point and the new allowance applies immediately.',
  },
  {
    q: 'Can I cancel?',
    a: 'Yes, from the billing page, in one click. You keep access until the end of the period you have already paid for, and your saved reports stay readable afterwards.',
  },
  {
    q: 'Is this affiliated with Amazon?',
    a: BRAND.amazonDisclaimer,
  },
];

export function Faq() {
  return (
    <section id="faq" className="section scroll-mt-16 border-b">
      <div className="container">
        <div className="mx-auto max-w-3xl">
          <div className="text-center">
            <span className="eyebrow">FAQ</span>
            <h2 className="h2 mt-3">Questions worth asking first</h2>
          </div>

          <Accordion type="single" collapsible className="mt-10">
            {FAQS.map((faq, i) => (
              <AccordionItem key={faq.q} value={`item-${i}`}>
                <AccordionTrigger>{faq.q}</AccordionTrigger>
                <AccordionContent>{faq.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
