import { readFileSync, writeFileSync } from 'node:fs';

/**
 * Builds the demo's CSS entry from the app's own globals.css.
 *
 * The app ships a `.dark` class that Next toggles. An Artifact has three theme states
 * instead: an explicit data-theme stamp either way, and an unstamped default where only
 * prefers-color-scheme separates them. So the dark tokens are re-emitted against all
 * three selectors, derived from globals.css rather than copied, so the two cannot drift.
 */
const source = readFileSync('src/app/globals.css', 'utf8');

const darkBlock = source.match(/\.dark\s*\{([\s\S]*?)\n  \}/);
if (!darkBlock) throw new Error('Could not find the .dark token block in globals.css');
const tokens = darkBlock[1].replace(/^\n/, '').replace(/\n$/, '');

writeFileSync(
  'demo/demo.css',
  `${source}

/* --- Artifact theming ---------------------------------------------------- */
/* Generated by demo/make-css.mjs from the .dark block above. Do not edit. */

@layer base {
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme='light']) {
${tokens}
    }
  }

  :root[data-theme='dark'] {
${tokens}
  }
}

@layer base {
  html {
    scroll-behavior: smooth;
  }
  @media (prefers-reduced-motion: reduce) {
    html {
      scroll-behavior: auto;
    }
    *,
    *::before,
    *::after {
      animation-duration: 0.01ms !important;
      animation-iteration-count: 1 !important;
      transition-duration: 0.01ms !important;
    }
  }
  :focus-visible {
    outline: 2px solid hsl(var(--ring));
    outline-offset: 2px;
  }
}
`,
);
console.log('demo/demo.css written');
